const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.SMTP_PORT || '587', 10),
  secure: process.env.SMTP_PORT === '465',
  auth: {
    user: process.env.SMTP_USER || '',
    pass: process.env.SMTP_PASS || '',
  },
});

async function sendContactEmail(name, email, message) {
  const mailUser = process.env.SMTP_USER;
  const mailPass = process.env.SMTP_PASS;

  if (!mailUser || !mailPass) {
    console.log('--------------------------------------------------');
    console.log('SIMULATED EMAIL NOTIFICATION (SMTP credentials missing):');
    console.log(`To: ${process.env.SMTP_TO || 'pavankumarch326@gmail.com'}`);
    console.log(`From: ${email} (${name})`);
    console.log(`Subject: New Portfolio Contact Message from ${name}`);
    console.log(`Body:\n${message}`);
    console.log('--------------------------------------------------');
    return false;
  }

  const mailOptions = {
    from: `"${name}" <${mailUser}>`,
    replyTo: email,
    to: process.env.SMTP_TO || mailUser,
    subject: `💼 Portfolio: New Contact Message from ${name}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 10px rgba(0,0,0,0.05);">
        <div style="background: linear-gradient(135deg, #7c4dff, #ff4081); padding: 24px; text-align: center; color: white;">
          <h2 style="margin: 0; font-size: 24px;">New Contact Message Received</h2>
          <p style="margin: 4px 0 0 0; opacity: 0.9;">Via your Portfolio Website</p>
        </div>
        <div style="padding: 24px; background-color: #fafafa;">
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; color: #666; font-weight: bold; width: 100px;">Sender Name:</td>
              <td style="padding: 8px 0; color: #333;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #666; font-weight: bold;">Sender Email:</td>
              <td style="padding: 8px 0; color: #333;"><a href="mailto:${email}" style="color: #7c4dff; text-decoration: none;">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #666; font-weight: bold;">Received At:</td>
              <td style="padding: 8px 0; color: #333;">${new Date().toLocaleString()}</td>
            </tr>
          </table>
          <hr style="border: 0; border-top: 1px solid #eeeeee; margin: 20px 0;" />
          <h4 style="color: #333; margin: 0 0 8px 0;">Message Content:</h4>
          <div style="background-color: white; border: 1px solid #e0e0e0; border-radius: 6px; padding: 16px; color: #444; line-height: 1.6; white-space: pre-wrap;">${message}</div>
          <div style="text-align: center; margin-top: 24px;">
            <a href="mailto:${email}" style="display: inline-block; background-color: #7c4dff; color: white; padding: 12px 24px; border-radius: 4px; text-decoration: none; font-weight: bold; box-shadow: 0 4px 6px rgba(124, 77, 255, 0.2);">Reply to ${name}</a>
          </div>
        </div>
        <div style="background-color: #f0f0f0; text-align: center; padding: 12px; font-size: 12px; color: #888;">
          This email was auto-generated by your portfolio web server.
        </div>
      </div>
    `,
  };

  await transporter.sendMail(mailOptions);
  return true;
}


const app = express();

app.use(cors({ origin: '*' }));
app.use(express.json());

const DEFAULT_PROJECTS = [
  {
    _id: 'fallback-1',
    title: 'Full-Stack MERN Application',
    description:
      'End-to-end web application built with MongoDB, Express.js, React, and Node.js. Features RESTful APIs, state management, routing, and a dynamic component-based UI.',
    techStack: ['MongoDB', 'Express.js', 'React', 'Node.js'],
    githubUrl: 'https://github.com/PavankumarCH22',
    featured: true,
  },
  {
    _id: 'fallback-2',
    title: 'Personal Portfolio',
    description:
      'Responsive portfolio website showcasing projects and skills. Built with React and Tailwind CSS with smooth animations and a clean modern design.',
    techStack: ['React', 'CSS', 'JavaScript'],
    githubUrl: 'https://github.com/PavankumarCH22',
    featured: true,
  },
  {
    _id: 'fallback-3',
    title: 'Frontend UI Projects',
    description:
      'Collection of front-end projects applying HTML, CSS, and JavaScript to build clean, user-friendly interfaces with modern design patterns.',
    techStack: ['HTML', 'CSS', 'JavaScript'],
    githubUrl: 'https://github.com/PavankumarCH22',
    featured: false,
  },
];

const memoryMessages = [];
let isConnected = false;

async function connectDB() {
  if (isConnected) return true;

  const uri = process.env.MONGODB_URI;
  if (!uri || !/^mongodb(\+srv)?:\/\//.test(uri)) {
    return false;
  }

  await mongoose.connect(uri);
  isConnected = true;
  return true;
}

const projectSchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: { type: String, required: true },
  techStack: [String],
  githubUrl: String,
  liveUrl: String,
  featured: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now },
});

const messageSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true },
  message: { type: String, required: true },
  createdAt: { type: Date, default: Date.now },
});

const Project = mongoose.models.Project || mongoose.model('Project', projectSchema);
const Message = mongoose.models.Message || mongoose.model('Message', messageSchema);

app.get('/api/projects', async (req, res) => {
  try {
    const connected = await connectDB();
    if (!connected) {
      return res.json({ success: true, data: DEFAULT_PROJECTS, source: 'fallback' });
    }

    const projects = await Project.find().sort({ featured: -1, createdAt: -1 });
    res.json({ success: true, data: projects });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

app.post('/api/projects', async (req, res) => {
  try {
    const connected = await connectDB();
    if (!connected) {
      return res.status(503).json({
        success: false,
        error: 'MongoDB is not configured. Add a valid MONGODB_URI to create projects.',
      });
    }

    const project = await Project.create(req.body);
    res.status(201).json({ success: true, data: project });
  } catch (err) {
    res.status(400).json({ success: false, error: err.message });
  }
});

app.post('/api/seed', async (req, res) => {
  try {
    const connected = await connectDB();
    if (!connected) {
      return res.json({ success: true, data: DEFAULT_PROJECTS, source: 'fallback' });
    }

    await Project.deleteMany({});
    const projects = await Project.insertMany(DEFAULT_PROJECTS.map(({ _id, ...project }) => project));
    res.json({ success: true, data: projects });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

app.post('/api/contact', async (req, res) => {
  try {
    const { name, email, message } = req.body;
    if (!name || !email || !message) {
      return res.status(400).json({ success: false, error: 'All fields are required.' });
    }

    const connected = await connectDB();
    let msg;
    let source;

    if (!connected) {
      msg = {
        _id: `memory-${Date.now()}`,
        name,
        email,
        message,
        createdAt: new Date(),
      };
      memoryMessages.unshift(msg);
      source = 'memory';
    } else {
      msg = await Message.create({ name, email, message });
    }

    // Attempt to send email in the background (don't block the API response)
    sendContactEmail(name, email, message).catch(err => {
      console.error('Nodemailer failed to send email:', err);
    });

    res.status(201).json({ success: true, data: msg, ...(source ? { source } : {}) });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

app.get('/api/messages', async (req, res) => {
  try {
    const connected = await connectDB();
    if (!connected) {
      return res.json({ success: true, data: memoryMessages, source: 'memory' });
    }

    const messages = await Message.find().sort({ createdAt: -1 });
    res.json({ success: true, data: messages });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

app.delete('/api/messages/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const connected = await connectDB();
    if (!connected) {
      const index = memoryMessages.findIndex(m => m._id === id);
      if (index !== -1) {
        memoryMessages.splice(index, 1);
        return res.json({ success: true, message: 'Message deleted from memory.' });
      }
      return res.status(404).json({ success: false, error: 'Message not found in memory.' });
    }

    const result = await Message.findByIdAndDelete(id);
    if (!result) {
      return res.status(404).json({ success: false, error: 'Message not found in database.' });
    }
    res.json({ success: true, message: 'Message deleted successfully.' });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

app.delete('/api/projects/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const connected = await connectDB();
    if (!connected) {
      return res.status(503).json({
        success: false,
        error: 'Database operation unavailable in fallback mode.',
      });
    }

    const result = await Project.findByIdAndDelete(id);
    if (!result) {
      return res.status(404).json({ success: false, error: 'Project not found.' });
    }
    res.json({ success: true, message: 'Project deleted successfully.' });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

app.post('/api/admin/auth', (req, res) => {
  const { password } = req.body;
  const adminPassword = process.env.ADMIN_PASSWORD || 'admin123';
  
  if (password === adminPassword) {
    return res.json({ success: true, token: 'authenticated_portfolio_session' });
  }
  
  res.status(401).json({ success: false, error: 'Invalid admin access password.' });
});

module.exports = app;
