const fs = require('fs');
const path = require('path');
const nodemailer = require('nodemailer');

// Load environment variables from parent directory .env
const envPath = path.join(__dirname, '..', '.env');
if (fs.existsSync(envPath)) {
  const env = fs.readFileSync(envPath, 'utf8');
  for (const line of env.split(/\r?\n/)) {
    const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
    if (match && !process.env[match[1]]) {
      process.env[match[1]] = (match[2] || '').trim();
    }
  }
}

const smtpHost = process.env.SMTP_HOST || 'smtp.gmail.com';
const smtpPort = parseInt(process.env.SMTP_PORT || '587', 10);
const smtpUser = process.env.SMTP_USER || '';
const smtpPass = process.env.SMTP_PASS || '';
const smtpTo = process.env.SMTP_TO || smtpUser;

console.log('==================================================');
console.log('       Nodemailer Test Email Configuration        ');
console.log('==================================================');
console.log(`SMTP Host: ${smtpHost}`);
console.log(`SMTP Port: ${smtpPort}`);
console.log(`SMTP User: ${smtpUser}`);
console.log(`SMTP To:   ${smtpTo}`);
console.log(`SMTP Pass: ${smtpPass ? '******** (configured)' : '(not configured)'}`);
console.log('==================================================\n');

if (!smtpUser || !smtpPass) {
  console.error('❌ Error: SMTP_USER and SMTP_PASS must be configured in your .env file.');
  process.exit(1);
}

if (smtpPass.includes('xxxx')) {
  console.warn('⚠️ Warning: SMTP_PASS appears to be using the placeholder value "xxxx_xxxx_xxxx_xxxx".');
  console.log('\nTo set up real email notifications via Gmail, please follow these steps:');
  console.log('1. Go to your Google Account (https://myaccount.google.com).');
  console.log('2. Enable 2-Step Verification if it is not already enabled.');
  console.log('3. Search for "App Passwords" in the search bar.');
  console.log('4. Create a new app password (select app: "Other", name it e.g. "Portfolio").');
  console.log('5. Copy the 16-character code and paste it in your .env file as SMTP_PASS.');
  console.log('\nWe will attempt to send using the current credentials anyway, but it will likely fail.\n');
}

const transporter = nodemailer.createTransport({
  host: smtpHost,
  port: smtpPort,
  secure: smtpPort === 465, // true for 465, false for other ports
  auth: {
    user: smtpUser,
    pass: smtpPass,
  },
});

const mailOptions = {
  from: `"Nodemailer Test" <${smtpUser}>`,
  to: smtpTo,
  subject: '🧪 Nodemailer Test Email',
  text: `Hello! This is a test email sent from your Node.js application.\n\nSent at: ${new Date().toLocaleString()}`,
  html: `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 10px rgba(0,0,0,0.05);">
      <div style="background: linear-gradient(135deg, #4f46e5, #06b6d4); padding: 24px; text-align: center; color: white;">
        <h2 style="margin: 0; font-size: 24px;">Connection Test Successful!</h2>
        <p style="margin: 4px 0 0 0; opacity: 0.9;">Nodemailer is configured correctly</p>
      </div>
      <div style="padding: 24px; background-color: #fafafa;">
        <p>Hello,</p>
        <p>This test email confirms that your Node.js backend can successfully connect to the SMTP server and send messages.</p>
        <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
          <tr>
            <td style="padding: 8px 0; color: #666; font-weight: bold; width: 120px;">SMTP Host:</td>
            <td style="padding: 8px 0; color: #333;">${smtpHost}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #666; font-weight: bold;">SMTP Port:</td>
            <td style="padding: 8px 0; color: #333;">${smtpPort}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #666; font-weight: bold;">Sender User:</td>
            <td style="padding: 8px 0; color: #333;">${smtpUser}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #666; font-weight: bold;">Recipient To:</td>
            <td style="padding: 8px 0; color: #333;">${smtpTo}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #666; font-weight: bold;">Sent Time:</td>
            <td style="padding: 8px 0; color: #333;">${new Date().toLocaleString()}</td>
          </tr>
        </table>
        <hr style="border: 0; border-top: 1px solid #eeeeee; margin: 20px 0;" />
        <p style="color: #666; font-size: 14px; line-height: 1.5;">You can now safely use these SMTP details to receive emails from your portfolio website's contact form.</p>
      </div>
      <div style="background-color: #f0f0f0; text-align: center; padding: 12px; font-size: 12px; color: #888;">
        This email was auto-generated by your nodemailer test script.
      </div>
    </div>
  `,
};

console.log('Sending test email...');

transporter.sendMail(mailOptions)
  .then(info => {
    console.log('\n✅ Success! Email sent successfully.');
    console.log(`Response: ${info.response}`);
    console.log(`Message ID: ${info.messageId}`);
  })
  .catch(err => {
    console.error('\n❌ Error: Failed to send email.');
    console.error(err);
  });
